//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string appId { get; set; }
        public string phone { get; set; }
        public string Password { get; set; }
        public string token { get; set; }
        public string name { get; set; }
        public Nullable<int> status { get; set; }
        public string email { get; set; }
        public string createDate { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
    }
}
