//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YLMDBDBEntities : DbContext
    {
        public YLMDBDBEntities()
            : base("name=YLMDBDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminMenu> AdminMenu { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Article> Article { get; set; }
        public DbSet<ArticleTag> ArticleTag { get; set; }
        public DbSet<Channel> Channel { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<HelpCenter> HelpCenter { get; set; }
        public DbSet<HIkVisionCamera> HIkVisionCamera { get; set; }
        public DbSet<HIkVisionPassenger> HIkVisionPassenger { get; set; }
        public DbSet<IntelligentData> IntelligentData { get; set; }
        public DbSet<IntelligentData0> IntelligentData0 { get; set; }
        public DbSet<IntelligentData1> IntelligentData1 { get; set; }
        public DbSet<IntelligentData2> IntelligentData2 { get; set; }
        public DbSet<IntelligentData3> IntelligentData3 { get; set; }
        public DbSet<IntelligentData4> IntelligentData4 { get; set; }
        public DbSet<IntelligentData5> IntelligentData5 { get; set; }
        public DbSet<IntelligentData6> IntelligentData6 { get; set; }
        public DbSet<IntelligentData7> IntelligentData7 { get; set; }
        public DbSet<IntelligentData8> IntelligentData8 { get; set; }
        public DbSet<IntelligentData9> IntelligentData9 { get; set; }
        public DbSet<IntelligentDataDH> IntelligentDataDH { get; set; }
        public DbSet<Log4net> Log4net { get; set; }
        public DbSet<LoginInfo> LoginInfo { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Province> Province { get; set; }
        public DbSet<QYLMailInfo> QYLMailInfo { get; set; }
        public DbSet<QYLPaiBanInfo> QYLPaiBanInfo { get; set; }
        public DbSet<QYLRecordInfo> QYLRecordInfo { get; set; }
        public DbSet<QYLUserInfo> QYLUserInfo { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SolarData> SolarData { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<UserSessionData> UserSessionData { get; set; }
        public DbSet<VerifyCode> VerifyCode { get; set; }
        public DbSet<VerifyCodeForPhone> VerifyCodeForPhone { get; set; }
        public DbSet<YLDeviceidData> YLDeviceidData { get; set; }
        public DbSet<YLMDBAuthorizationInfo> YLMDBAuthorizationInfo { get; set; }
        public DbSet<YLMDBBindEquipment> YLMDBBindEquipment { get; set; }
        public DbSet<YLMDBBrands> YLMDBBrands { get; set; }
        public DbSet<YLMDBByRecords> YLMDBByRecords { get; set; }
        public DbSet<YLMDBCategory> YLMDBCategory { get; set; }
        public DbSet<YLMDBCheckPlan> YLMDBCheckPlan { get; set; }
        public DbSet<YLMDBCheckProject> YLMDBCheckProject { get; set; }
        public DbSet<YLMDBCheckProject_Cfg> YLMDBCheckProject_Cfg { get; set; }
        public DbSet<YLMDBCheckTask> YLMDBCheckTask { get; set; }
        public DbSet<YLMDBCheckTaskList> YLMDBCheckTaskList { get; set; }
        public DbSet<YLMDBChildUserRole> YLMDBChildUserRole { get; set; }
        public DbSet<YLMDBCmsArt> YLMDBCmsArt { get; set; }
        public DbSet<YLMDBCmsArtType> YLMDBCmsArtType { get; set; }
        public DbSet<YLMDBDate> YLMDBDate { get; set; }
        public DbSet<YLMDBGateway> YLMDBGateway { get; set; }
        public DbSet<YLMDBGLCheckProject> YLMDBGLCheckProject { get; set; }
        public DbSet<YLMDBHobby> YLMDBHobby { get; set; }
        public DbSet<YLMDBImage> YLMDBImage { get; set; }
        public DbSet<YLMDBInStore> YLMDBInStore { get; set; }
        public DbSet<YLMDBLogs> YLMDBLogs { get; set; }
        public DbSet<YLMDBMall> YLMDBMall { get; set; }
        public DbSet<YLMDBMember> YLMDBMember { get; set; }
        public DbSet<YLMDBReception> YLMDBReception { get; set; }
        public DbSet<YLMDBResolutionRecord> YLMDBResolutionRecord { get; set; }
        public DbSet<YLMDBResolutionRecord_HK> YLMDBResolutionRecord_HK { get; set; }
        public DbSet<YLMDBRosterGroup> YLMDBRosterGroup { get; set; }
        public DbSet<YLMDBSalesRecord> YLMDBSalesRecord { get; set; }
        public DbSet<YLMDBSalesTarget> YLMDBSalesTarget { get; set; }
        public DbSet<YLMDBScoreForm> YLMDBScoreForm { get; set; }
        public DbSet<YLMDBScoreInfo> YLMDBScoreInfo { get; set; }
        public DbSet<YLMDBSuggest> YLMDBSuggest { get; set; }
        public DbSet<YLMDBThreshold> YLMDBThreshold { get; set; }
        public DbSet<YLMDBType> YLMDBType { get; set; }
        public DbSet<YLMDBUserBelongs> YLMDBUserBelongs { get; set; }
        public DbSet<YLMDBUserInfo> YLMDBUserInfo { get; set; }
        public DbSet<YLMDBVersion> YLMDBVersion { get; set; }
        public DbSet<YLMDBVipType> YLMDBVipType { get; set; }
        public DbSet<YsPreset> YsPreset { get; set; }
    }
}
