//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIkVisionCamera
    {
        public int ID { get; set; }
        public int camera_id { get; set; }
        public string sys_code { get; set; }
        public string camera_name { get; set; }
        public int camera_type { get; set; }
        public System.DateTime create_time { get; set; }
        public int online_status { get; set; }
        public string devsn { get; set; }
    }
}
