//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIkVisionPassenger
    {
        public int id { get; set; }
        public int camera_id { get; set; }
        public int out_num { get; set; }
        public int in_num { get; set; }
        public int gatewayid { get; set; }
        public System.DateTime createtime { get; set; }
    }
}
