//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntelligentData6
    {
        public int DataID { get; set; }
        public int GatewayID { get; set; }
        public string IMEI { get; set; }
        public string MAC { get; set; }
        public System.DateTime DataDateTime { get; set; }
        public int InNum { get; set; }
        public int OutNum { get; set; }
        public Nullable<int> Flage { get; set; }
    }
}
