//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid LoginToken { get; set; }
        public System.DateTime LastAccessTime { get; set; }
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<double> OverDays { get; set; }
        public string ParentName { get; set; }
        public string DisplayName { get; set; }
        public string BusinessPermissionString { get; set; }
        public string ClientIP { get; set; }
        public int EnumLoginAccountType { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
