//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QYLPaiBanInfo
    {
        public int ID { get; set; }
        public Nullable<int> GatewayID { get; set; }
        public string DevSN { get; set; }
        public string strScheduleName { get; set; }
        public string sMonOnDuty1 { get; set; }
        public string sMonOffDuty1 { get; set; }
        public Nullable<int> MonType1 { get; set; }
        public Nullable<int> MonInterval1 { get; set; }
        public string sMonOnDuty2 { get; set; }
        public string sMonOffDuty2 { get; set; }
        public Nullable<int> MonType2 { get; set; }
        public Nullable<int> MonInterval2 { get; set; }
        public string sMonOnDuty3 { get; set; }
        public string sMonOffDuty3 { get; set; }
        public Nullable<int> MonType3 { get; set; }
        public Nullable<int> MonInterval3 { get; set; }
        public string sTueOnDuty1 { get; set; }
        public string sTueOffDuty1 { get; set; }
        public Nullable<int> TueType1 { get; set; }
        public Nullable<int> TueInterval1 { get; set; }
        public string sTueOnDuty2 { get; set; }
        public string sTueOffDuty2 { get; set; }
        public Nullable<int> TueType2 { get; set; }
        public Nullable<int> TueInterval2 { get; set; }
        public string sTueOnDuty3 { get; set; }
        public string sTueOffDuty3 { get; set; }
        public Nullable<int> TueType3 { get; set; }
        public Nullable<int> TueInterval3 { get; set; }
        public string sWedOnDuty1 { get; set; }
        public string sWedOffDuty1 { get; set; }
        public Nullable<int> WedType1 { get; set; }
        public Nullable<int> WedInterval1 { get; set; }
        public string sWedOnDuty2 { get; set; }
        public string sWedOffDuty2 { get; set; }
        public Nullable<int> WedType2 { get; set; }
        public Nullable<int> WedInterval2 { get; set; }
        public string sWedOnDuty3 { get; set; }
        public string sWedOffDuty3 { get; set; }
        public Nullable<int> WedType3 { get; set; }
        public Nullable<int> WedInterval3 { get; set; }
        public string sThuOnDuty1 { get; set; }
        public string sThuOffDuty1 { get; set; }
        public Nullable<int> ThuType1 { get; set; }
        public Nullable<int> ThuInterval1 { get; set; }
        public string sThuOnDuty2 { get; set; }
        public string sThuOffDuty2 { get; set; }
        public Nullable<int> ThuType2 { get; set; }
        public Nullable<int> ThuInterval2 { get; set; }
        public string sThuOnDuty3 { get; set; }
        public string sThuOffDuty3 { get; set; }
        public Nullable<int> ThuType3 { get; set; }
        public Nullable<int> ThuInterval3 { get; set; }
        public string sFriOnDuty1 { get; set; }
        public string sFriOffDuty1 { get; set; }
        public Nullable<int> FriType1 { get; set; }
        public Nullable<int> FriInterval1 { get; set; }
        public string sFriOnDuty2 { get; set; }
        public string sFriOffDuty2 { get; set; }
        public Nullable<int> FriType2 { get; set; }
        public Nullable<int> FriInterval2 { get; set; }
        public string sFriOnDuty3 { get; set; }
        public string sFriOffDuty3 { get; set; }
        public Nullable<int> FriType3 { get; set; }
        public Nullable<int> FriInterval3 { get; set; }
        public string sSatOnDuty1 { get; set; }
        public string sSatOffDuty1 { get; set; }
        public Nullable<int> SatType1 { get; set; }
        public Nullable<int> SatInterval1 { get; set; }
        public string sSatOnDuty2 { get; set; }
        public string sSatOffDuty2 { get; set; }
        public Nullable<int> SatType2 { get; set; }
        public Nullable<int> SatInterval2 { get; set; }
        public string sSatOnDuty3 { get; set; }
        public string sSatOffDuty3 { get; set; }
        public Nullable<int> SatType3 { get; set; }
        public Nullable<int> SatInterval3 { get; set; }
        public string sSunOnDuty1 { get; set; }
        public string sSunOffDuty1 { get; set; }
        public Nullable<int> SunType1 { get; set; }
        public Nullable<int> SunInterval1 { get; set; }
        public string sSunOnDuty2 { get; set; }
        public string sSunOffDuty2 { get; set; }
        public Nullable<int> SunType2 { get; set; }
        public Nullable<int> SunInterval2 { get; set; }
        public string sSunOnDuty3 { get; set; }
        public string sSunOffDuty3 { get; set; }
        public Nullable<int> SunType3 { get; set; }
        public Nullable<int> SunInterval3 { get; set; }
    }
}
