//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QYLUserInfo
    {
        public int ID { get; set; }
        public Nullable<int> GatewayID { get; set; }
        public int UserID { get; set; }
        public string strDevSn { get; set; }
        public string strUserName { get; set; }
        public Nullable<int> photoLen { get; set; }
        public string strBase64Photo { get; set; }
        public string phone { get; set; }
        public string DptId { get; set; }
        public Nullable<int> PushStatus { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
