//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YLApiEntities : DbContext
    {
        public YLApiEntities()
            : base("name=YLApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<AppIdLog> AppIdLog { get; set; }
        public DbSet<District> District { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<FeedBack> FeedBack { get; set; }
        public DbSet<Merchant> Merchant { get; set; }
        public DbSet<NodeList> NodeList { get; set; }
    }
}
