//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBCmsArtType
    {
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string SubName { get; set; }
        public string Pic { get; set; }
        public string Desc { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int IsDelete { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
