//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBVersion
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<int> Type { get; set; }
        public string Info { get; set; }
        public string URL { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
