//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBCheckTask
    {
        public int ID { get; set; }
        public string TaskName { get; set; }
        public int TaskCycle { get; set; }
        public string ActionTime { get; set; }
        public string ActionDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int ActionType { get; set; }
        public string CheckProjectID { get; set; }
        public string CheckProjectName { get; set; }
        public string CheckProjectIDBak { get; set; }
        public int MallID { get; set; }
        public int CheckPersonID { get; set; }
        public int CreatePersonID { get; set; }
        public int IsFinish { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
