//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBMember
    {
        public int ID { get; set; }
        public int MallID { get; set; }
        public int UserID { get; set; }
        public string vipId { get; set; }
        public string vipName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> vipType { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public string image4 { get; set; }
        public string image5 { get; set; }
        public string Manager { get; set; }
        public string Address { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ReceptionId { get; set; }
        public Nullable<int> IsEnable { get; set; }
        public string CustomerNo { get; set; }
        public string FaceinfoCode { get; set; }
        public Nullable<System.DateTime> BirthTime { get; set; }
        public string UserID1 { get; set; }
        public Nullable<int> FaceDBId { get; set; }
        public Nullable<int> EncoderId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
