//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBAuthorizationInfo
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string PassWord { get; set; }
        public string AppKey { get; set; }
        public string AppSecret { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
