//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBResolutionRecord_HK
    {
        public int ID { get; set; }
        public int GatewayID { get; set; }
        public string EquNo { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string FaceFrame { get; set; }
        public string PersonIds { get; set; }
        public Nullable<int> InNum { get; set; }
        public string VipId { get; set; }
        public string MsgId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
