//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBDate
    {
        public int ID { get; set; }
        public Nullable<int> hours { get; set; }
        public string weeks { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> type { get; set; }
        public string generation { get; set; }
        public Nullable<int> quarters { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<int> week { get; set; }
    }
}
