//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBBindEquipment
    {
        public int ID { get; set; }
        public int GatewayID { get; set; }
        public string DevSn { get; set; }
        public string DevName { get; set; }
        public int DevType { get; set; }
        public int IsOnline { get; set; }
        public int IsUpData { get; set; }
        public Nullable<int> PushType { get; set; }
        public string PushTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
