//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBCmsArt
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ArtTypeID { get; set; }
        public string Pic { get; set; }
        public string Desc { get; set; }
        public string Detail { get; set; }
        public string KeyWord { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string Issuer { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
