//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBSalesTarget
    {
        public int ID { get; set; }
        public int ShopID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> Money { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
