//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.YLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YLMDBScoreForm
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public int PrincipalID { get; set; }
        public int MallID { get; set; }
        public int CheckProjectID { get; set; }
        public decimal Score { get; set; }
        public string Remark { get; set; }
        public string PicUrl1 { get; set; }
        public string PicUrl2 { get; set; }
        public string PicUrl3 { get; set; }
        public string R_Remark { get; set; }
        public string R_PicUrl1 { get; set; }
        public string R_PicUrl2 { get; set; }
        public string R_PicUrl3 { get; set; }
        public int Flag { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
